#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.5.0
// Descriptor size: 47 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 8 |
// +----------+-------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x05, 0x01,    // UsagePage(Generic Desktop[0x0001])
    0x09, 0x05,    // UsageId(Gamepad[0x0005])
    0xA1, 0x01,    // Collection(Application)
    0x85, 0x01,    //     ReportId(1)
    0x09, 0x30,    //     UsageId(X[0x0030])
    0x09, 0x31,    //     UsageId(Y[0x0031])
    0x09, 0x32,    //     UsageId(Z[0x0032])
    0x09, 0x33,    //     UsageId(Rx[0x0033])
    0x09, 0x34,    //     UsageId(Ry[0x0034])
    0x09, 0x35,    //     UsageId(Rz[0x0035])
    0x15, 0x81,    //     LogicalMinimum(-127)
    0x25, 0x7F,    //     LogicalMaximum(127)
    0x95, 0x06,    //     ReportCount(6)
    0x75, 0x08,    //     ReportSize(8)
    0x81, 0x02,    //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x09,    //     UsagePage(Button[0x0009])
    0x19, 0x01,    //     UsageIdMin(Button 1[0x0001])
    0x29, 0x10,    //     UsageIdMax(Button 16[0x0010])
    0x15, 0x00,    //     LogicalMinimum(0)
    0x25, 0x01,    //     LogicalMaximum(1)
    0x95, 0x10,    //     ReportCount(16)
    0x75, 0x01,    //     ReportSize(1)
    0x81, 0x02,    //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,          // EndCollection()
};

#pragma pack(push,1)

#define HID_REPORT_INPUT1_ID (1)
struct HidReportInput1
{
    uint8_t ReportId = HID_REPORT_INPUT1_ID;
    uint8_t Payload[8];
};

#pragma pack(pop)